/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as PaqueteIdRouteImport } from './routes/paquete.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaqueteIdRoute = PaqueteIdRouteImport.update({
  id: '/paquete/$id',
  path: '/paquete/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/paquete/$id': typeof PaqueteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/paquete/$id': typeof PaqueteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/paquete/$id': typeof PaqueteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categoria/$slug' | '/paquete/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categoria/$slug' | '/paquete/$id'
  id: '__root__' | '/' | '/categoria/$slug' | '/paquete/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  PaqueteIdRoute: typeof PaqueteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paquete/$id': {
      id: '/paquete/$id'
      path: '/paquete/$id'
      fullPath: '/paquete/$id'
      preLoaderRoute: typeof PaqueteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  PaqueteIdRoute: PaqueteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
